In [2]:
import pandas as pd
import numpy as np

import nltk
from nltk.tokenize import word_tokenize
from nltk import PorterStemmer
from nltk import WordNetLemmatizer
from nltk.corpus import stopwords

import re

from sklearn.feature_extraction import text
from sklearn.feature_extraction.text import CountVectorizer

import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
from sklearn.svm import SVR

In [4]:
cd

/Users/brianrochford


In [9]:
df = pd.read_csv('winemag_fin.csv', index_col = 0)

/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:2714: DtypeWarning: Columns (9,10,11) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [10]:
df.describe()

points          price
count  280901.000000  258210.000000
mean       88.146934      34.177162
std         3.151528      38.611708
min        80.000000       4.000000
25%        86.000000      16.000000
50%        88.000000      25.000000
75%        90.000000      40.000000
max       100.000000    3300.000000

In [8]:
df = df.drop_duplicates()
df = df.drop(columns=['Unnamed: 0','designation','region_1','region_2','province','taster_name','taster_twitter_handle','title','variety','winery'])

KeyError: "['Unnamed: 0'] not found in axis"

In [119]:
df = df.dropna()

In [12]:
df_noDups = df.drop_duplicates()[['description','region_1','points','price']].dropna()

In [104]:
df = df.drop_duplicates()
df= df.dropna()

In [105]:
df.region_1.value_counts()

Columbia Valley (WA)         2281
Willamette Valley            1253
Russian River Valley         1175
Napa Valley                  1046
Paso Robles                   838
                             ... 
Sierra Pelona Valley            1
York Mountain                   1
Sonoma-Mendocino                1
Sonoma County-Lake County       1
San Diego County                1
Name: region_1, Length: 171, dtype: int64

In [13]:
data1 = pd.DataFrame(df.region_1.value_counts())
data1.columns = ['counts'] 
data1

counts
Napa Valley                               10689
Columbia Valley (WA)                       9099
Russian River Valley                       6662
California                                 6091
Mendoza                                    5887
Paso Robles                                5403
Willamette Valley                          4397
Alsace                                     3737
Rioja                                      3362
Brunello di Montalcino                     3216
Sonoma County                              3099
Toscana                                    3082
Barolo                                     2997
Champagne                                  2982
Sonoma Coast                               2947
Finger Lakes                               2937
Sicilia                                    2626
Carneros                                   2457
Dry Creek Valley                           2337
Santa Barbara County                       2319
Walla Walla Valley (WA)                    2291
Yakima Valley                              2159
Chianti Classico                           2091
Sta. Rita Hills                            1958
Alexander Valley                           1923
Santa Lucia Highlands                      1768
Santa Ynez Valley                          1710
Central Coast                              1699
Lodi                                       1677
Sonoma Valley                              1632
...                                         ...
Château-Chalon                                1
Côtes du Roussillon Les Aspres                1
Falanghina del Molise                         1
Sardon de Duero                               1
Frascati                                      1
Bellarine Peninsula                           1
Coda di Volpe d'Irpinia                       1
Côtes de Saint-Mont                           1
Lake-Sonoma-Napa                              1
Recioto della Valpolicella Valpantena         1
Geographe                                     1
Coteaux du Tricastin                          1
Mendocino-Amador-Napa                         1
Stanislaus County                             1
Maury Sec                                     1
Vin de Pays de Caux                           1
Cacc’e Mmitte di Lucera                       1
Hawaii                                        1
Listrac                                       1
Vin de Pays de Côtes du Tarn                  1
Gutturnio Classico Superiore                  1
Nasco di Cagliari                             1
Benaco Bresciano                              1
Vin de Pays des Sables du Golfe du Lion       1
Cabernet de Saumur                            1
San Martino della Battaglia                   1
Colli del Limbara                             1
Napa-Monterey-Mendocino                       1
Napa-Sonoma-Monterey                          1
Arlanza                                       1

[1332 rows x 1 columns]

In [14]:
data2 = df.groupby('region_1').agg({'description':lambda x: ' '.join(x), 
                         'points':'mean', 
                         'price':'mean'})

In [16]:
df_joinCountRegion = data1.join(data2)

In [20]:
df_joinCountRegion

counts  \
Napa Valley                               10689   
Columbia Valley (WA)                       9099   
Russian River Valley                       6662   
California                                 6091   
Mendoza                                    5887   
Paso Robles                                5403   
Willamette Valley                          4397   
Alsace                                     3737   
Rioja                                      3362   
Brunello di Montalcino                     3216   
Sonoma County                              3099   
Toscana                                    3082   
Barolo                                     2997   
Champagne                                  2982   
Sonoma Coast                               2947   
Finger Lakes                               2937   
Sicilia                                    2626   
Carneros                                   2457   
Dry Creek Valley                           2337   
Santa Barbara County                       2319   
Walla Walla Valley (WA)                    2291   
Yakima Valley                              2159   
Chianti Classico                           2091   
Sta. Rita Hills                            1958   
Alexander Valley                           1923   
Santa Lucia Highlands                      1768   
Santa Ynez Valley                          1710   
Central Coast                              1699   
Lodi                                       1677   
Sonoma Valley                              1632   
...                                         ...   
Château-Chalon                                1   
Côtes du Roussillon Les Aspres                1   
Falanghina del Molise                         1   
Sardon de Duero                               1   
Frascati                                      1   
Bellarine Peninsula                           1   
Coda di Volpe d'Irpinia                       1   
Côtes de Saint-Mont                           1   
Lake-Sonoma-Napa                              1   
Recioto della Valpolicella Valpantena         1   
Geographe                                     1   
Coteaux du Tricastin                          1   
Mendocino-Amador-Napa                         1   
Stanislaus County                             1   
Maury Sec                                     1   
Vin de Pays de Caux                           1   
Cacc’e Mmitte di Lucera                       1   
Hawaii                                        1   
Listrac                                       1   
Vin de Pays de Côtes du Tarn                  1   
Gutturnio Classico Superiore                  1   
Nasco di Cagliari                             1   
Benaco Bresciano                              1   
Vin de Pays des Sables du Golfe du Lion       1   
Cabernet de Saumur                            1   
San Martino della Battaglia                   1   
Colli del Limbara                             1   
Napa-Monterey-Mendocino                       1   
Napa-Sonoma-Monterey                          1   
Arlanza                                       1   

                                                                               description  \
Napa Valley                              Soft, supple plum envelopes an oaky structure ...   
Columbia Valley (WA)                     Aromas of cranberry, barrel spice and herb are...   
Russian River Valley                     This wine is put together from multiple vineya...   
California                               Very deep in color and spicy-smoky in flavor, ...   
Mendoza                                  Raw black-cherry aromas are direct and simple ...   
Paso Robles                              This wine from the Geneseo district offers aro...   
Willamette Valley                        Tart and snappy, the flavors of lime flesh and...   
Alsace                                   This dry and restrained wine offers spice in p...   
Rioja                           

In [19]:
df_joinCountRegion.to_excel('regionCountMerge.xlsx')

In [21]:
df.region_1.value_counts()[:350]

Napa Valley                                           10689
Columbia Valley (WA)                                   9099
Russian River Valley                                   6662
California                                             6091
Mendoza                                                5887
Paso Robles                                            5403
Willamette Valley                                      4397
Alsace                                                 3737
Rioja                                                  3362
Brunello di Montalcino                                 3216
Sonoma County                                          3099
Toscana                                                3082
Barolo                                                 2997
Champagne                                              2982
Sonoma Coast                                           2947
Finger Lakes                                           2937
Sicilia                                 

In [22]:
remove_non_alphabets = lambda x: re.sub(r'[^a-zA-Z]',' ',x)

tokenize = lambda x: word_tokenize(x)

ps = PorterStemmer()

stem = lambda w: [ ps.stem(x) for x in w ]

lemmatizer = WordNetLemmatizer()
leammtizer = lambda x: [ lemmatizer.lemmatize(word) for word in x ]

remove_stop = lambda x: [w for w in x if w not in stop]

In [42]:
#df_joinCountRegion

In [37]:

#df.region_1.value_counts()[:350]
df_joinCountRegion2 = df_joinCountRegion.iloc[0].value_counts()[:350]
df_joinCountRegion3 = pd.DataFrame(df_joinCountRegion2)
#df_joinCountRegion3

In [38]:
df = df_joinCountRegion3
df.describe()

Napa Valley
count          4.0
mean           1.0
std            0.0
min            1.0
25%            1.0
50%            1.0
75%            1.0
max            1.0

In [40]:
#df

In [41]:
print('Processing : [=', end='')
df['description'] = df['description'].apply(remove_non_alphabets)
print('=', end='')
df['description'] = df['description'].apply(tokenize)
print('=', end='')
stop = text.ENGLISH_STOP_WORDS
df['description'] = df['description'].apply(remove_stop)
print('=', end='')
df['description'] = df['description'].apply(stem)
print('=', end='')
df['description'] = df['description'].apply(leammtizer)
print('=', end='')
df['description'] = df['description'].apply(lambda x: ' '.join(x))
print(']')

Processing : [=

KeyError: 'description'

In [44]:
cd


/Users/brianrochford


In [45]:
df = pd.read_csv('preprocessedwine.csv', index_col= 0)
df = df.dropna()

In [52]:
df.columns

Index(['country', 'description', 'points', 'price'], dtype='object')

In [46]:
Q1 = np.percentile(df['price'], 25,
                   interpolation = 'midpoint')
 
Q3 = np.percentile(df['price'], 75,
                   interpolation = 'midpoint')
IQR = Q3 - Q1
df = df[df.price < (Q3+1.5*IQR)+1]

In [47]:
def get_sample(df,x):
    df = df.sample(frac=x, replace=False, random_state=1)
    df = df.reset_index(drop=True)
    return df

def bow_vector(df):
    bow_vectorizer=CountVectorizer(min_df=1, max_features=5000, ngram_range=(1,1))

    bow_features = bow_vectorizer.fit_transform(df.description)

    df_bow = pd.DataFrame(bow_features.toarray(),
                      columns=bow_vectorizer.get_feature_names())
    df_bow = df_bow.drop(columns=['price'])
    
    return df_bow

def jointwo(df,df_bow):
    df = df.join(df_bow)
    df = df.drop(columns=['country','description'])
    df = df.fillna(0)
    return df

In [48]:
def run_random_for(df):
    X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['price']), df.price, test_size=0.30, random_state=42)
    regr = RandomForestRegressor()
    regr.fit(X_train, y_train)
    return regr, X_test, y_test
    
def run_svr(df):
    X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['price']), df.price, test_size=0.30, random_state=42)
    regressor = SVR(kernel='rbf')
    regressor.fit(X_train,y_train)
    return regressor, X_test, y_test

In [49]:
df1 = get_sample(df,0.1)
df1 = df1.head(int(len(df)*(100/100)))
df_bow = bow_vector(df1)
df2 = jointwo(df1,df_bow)

In [54]:
df2

points  price  abbrevi  abil  abl  abli  abound  about  abras  abrupt  \
0          89   18.0        0     0    0     0       0      0      0       0   
1          92   35.0        0     0    0     0       0      0      0       0   
2          80   16.0        0     0    0     0       0      0      0       0   
3          87   19.0        0     0    0     0       0      0      0       0   
4          86   15.0        0     0    0     0       0      0      0       0   
...       ...    ...      ...   ...  ...   ...     ...    ...    ...     ...   
25810      86   20.0        0     0    0     0       0      0      0       0   
25811      87   14.0        0     0    0     0       0      0      0       0   
25812      85   23.0        0     0    0     0       0      0      0       0   
25813      88   12.0        0     0    0     0       0      0      0       0   
25814      85   17.0        0     0    0     0       0      0      0       0   

       ...  zesti  zin  zinfandel  zing  zingi  zip  zippi  zone  zonin  \
0      ...      0    0          0     0      0    0      0     0      0   
1      ...      0    0          0     0      0    0      0     0      0   
2      ...      0    0          0     0      0    0      0     0      0   
3      ...      0    0          0     0      0    0      0     0      0   
4      ...      0    0          0     0      0    0      0     0      0   
...    ...    ...  ...        ...   ...    ...  ...    ...   ...    ...   
25810  ...      0    0          0     0      0    0      0     0      0   
25811  ...      0    0          0     0      0    0      0     0      0   
25812  ...      0    0          0     0      0    0      0     0      0   
25813  ...      0    0          0     0      0    0      0     0      0   
25814  ...      0    0          0     0      0    0      0     0      0   

       zweigelt  
0             1  
1             0  
2             0  
3             0  
4             0  
...         ...  
25810         0  
25811         0  
25812         0  
25813         0  
25814         0  

[25815 rows x 5001 columns]

In [53]:
df.region_1.value_counts()

AttributeError: 'DataFrame' object has no attribute 'region_1'

In [54]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

test = SelectKBest(score_func=chi2, k=4)
fit = test.fit(df2.drop(columns=['price']), df2.price)


np.set_printoptions(precision=3)
print(fit.scores_)

features = fit.transform(df2.drop(columns=['price']))

print(features[0:5,:])

[798.326  16.311  97.357 ...  39.8    20.113  43.687]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 1]
 [0 0 0 0]]


In [56]:
regr1, x_test1, y_test1 = run_random_for(df2)

In [55]:
fet_imp = pd.DataFrame({"names":x_test1.columns,
                       "importance":regr1.feature_importances_})
best_features = fet_imp.sort_values(by=['importance'],ascending =False).names[:100]

NameError: name 'x_test1' is not defined

In [ ]:
df3 = df1.head(int(len(df)*(30/100)))
df_bow1 = bow_vector(df3)
df_bow1 = df_bow1.filter(items=list(best_features))
df4 = jointwo(df3,df_bow1)

In [ ]:
regr2, x_test2, y_test2 = run_random_for(df4)
y_pred = regr2.predict(x_test2)

In [ ]:
mean_squared_error(y_test2, y_pred)