In [9]:
import pyforest


In [10]:
import matplotlib.pyplot as plt
import re
import os
import pandas as pd
import numpy as np

import nltk
from nltk.tokenize import word_tokenize
from nltk import PorterStemmer
from nltk import WordNetLemmatizer
from nltk.corpus import stopwords

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn import metrics
#import gensim

In [11]:
#!pip install gensim

In [41]:
import confusion_matrix

ModuleNotFoundError: No module named 'confusion_matrix'

In [4]:
cd

/Users/brianrochford


In [12]:
data = pd.read_csv("/Users/brianrochford/Downloads/Spam Email (1).csv")

In [13]:
data['CATEGORY'].value_counts()

0    3900
1    1896
Name: CATEGORY, dtype: int64

In [14]:
#Preprocessing
# remove non alphabets
remove_non_alphabets = lambda x: re.sub(r'[^a-zA-Z]',' ',x)

# tokenn alphabets-only list
tokenize = lambda x: word_tokenize(x)

# assign ps to a lambda function to run on each line of value
ps = PorterStemmer()
stem = lambda w: [ ps.stem(x) for x in w ]


lemmatizer = WordNetLemmatizer()
lemmtizer = lambda x: [ lemmatizer.lemmatize(word) for word in x ]

In [15]:
print('Processing : [=', end='')
data['MESSAGE'] = data['MESSAGE'].apply(remove_non_alphabets)
data['MESSAGE'] = data['MESSAGE'].apply(lambda x: re.sub(r'[^a-zA-Z]',' ',x))

print('=', end='')
data['MESSAGE'] = data['MESSAGE'].apply(tokenize)
print('=', end='')
data['MESSAGE'] = data['MESSAGE'].apply(stem)
print('=', end='')
data['MESSAGE'] = data['MESSAGE'].apply(lemmtizer)
print('=', end='')
data['MESSAGE'] = data['MESSAGE'].apply(lambda x: ' '.join(x))
print('] : Completed', end='')
data.head()

Processing : [=====] : Completed

CATEGORY                                            MESSAGE  \
0         1  dear homeown interest rate are at their lowest...   
1         1  attent thi is a must for all comput user new s...   
2         1  thi is a multi part messag in mime format next...   
3         1  import inform the new domain name are final av...   
4         1  thi is the bottom line If you can give away CD...   

                                FILE_NAME  
0  00249.5f45607c1bffe89f60ba1ec9f878039a  
1  00373.ebe8670ac56b04125c25100a36ab0510  
2  00214.1367039e50dc6b7adb0f2aa8aba83216  
3  00210.050ffd105bd4e006771ee63cabc59978  
4  00033.9babb58d9298daa2963d4f514193d7d6

## Train Testing

In [16]:
# split to 30 percent test data and 70 percent train data
# labels can be seen as y, an dependent variable
train_corpus, test_corpus, train_labels, test_labels = train_test_split(data["MESSAGE"],
                                                                        data["CATEGORY"],
                                                                        test_size=0.3)

## Machine Learning Features

In [17]:
#Bag of Words 


bow_vectorizer=CountVectorizer(min_df=30, max_df=0.90,max_features=5000,ngram_range=(1,1))
# print(bow_vectorizer)
#In short, fit is used to train the feature model, once it's trained you can use that model to apply to the text data
bow_train_features = bow_vectorizer.fit_transform(train_corpus)
#apply model to test data
bow_test_features = bow_vectorizer.transform(test_corpus)

In [18]:
bow_vectorizer_binary=CountVectorizer(min_df=30, max_df=0.90,max_features=5000,ngram_range=(1,1), binary=True)
# print(bow_vectorizer)
#In short, fit is used to train the feature model, once it's trained you can use that model to apply to the text data
bow_train_features_binary = bow_vectorizer_binary.fit_transform(train_corpus)
#apply model to test data
bow_test_features_binary = bow_vectorizer_binary.transform(test_corpus)

In [19]:
#print(bow_train_features_binary.shape)
#print(bow_train_features_binary)

In [20]:
#print(bow_train_features.shape)
#print(bow_train_features)

In [21]:
#print(bow_test_features.shape)
#print(bow_test_features)

In [22]:
count_array = bow_train_features.toarray()
df = pd.DataFrame(data=count_array,columns = bow_vectorizer.get_feature_names())
print(df.shape)
df.head(20)

(4057, 2483)


aa  ab  abil  abl  about  abov  absolut  abus  ac  accept  ...  yourself  \
0    0   0     0    0      0     0        0     0   0       0  ...         0   
1    0   0     0    0      0     0        0     0   0       0  ...         0   
2    0   0     0    0      0     0        0     0   0       1  ...         0   
3    0   0     0    0      0     0        0     0   0       0  ...         0   
4    0   0     0    0      0     0        0     0   0       0  ...         0   
5    0   0     0    0      2     0        0     0   0       0  ...         0   
6    0   0     0    0      0     0        0     2   0       0  ...         0   
7    0   0     0    0      1     0        0     0   0       0  ...         0   
8    0   0     0    0      1     0        0     0   0       0  ...         0   
9    0   0     0    0      0     0        0     0   0       0  ...         0   
10   0   0     0    0      0     0        0     0   0       0  ...         0   
11   0   0     0    0      0     0        0     0   0       0  ...         0   
12   0   0     0    0      0     0        0     0   0       0  ...         0   
13   0   0     0    0      1     0        0     0   0       0  ...         0   
14   0   0     0    0      0     0        0     0   0       0  ...         0   
15   0   0     0    0      0     0        0     0   0       0  ...         1   
16   0   0     0    0      0     0        0     0   0       0  ...         0   
17   0   0     0    0      1     0        0     0   0       0  ...         0   
18   0   0     0    0      0     0        0     0   0       0  ...         0   
19   0   0     0    0      1     0        0     0   0       0  ...         0   

    yr  yw  zd  zero  zip  zm  zt  zw  zzzz  
0    0   0   0     0    0   0   0   0     0  
1    0   0   0     0    0   0   0   0     0  
2    0   0   0     0    0   0   0   0     0  
3    0   0   0     0    0   0   0   0     0  
4    0   0   0     0    0   0   0   0     0  
5    0   0   0     0    0   0   0   0     0  
6    0   0   0     0    0   0   0   0     0  
7    0   0   0     0    0   0   0   0     0  
8    0   0   0     0    0   0   0   0     0  
9    0   0   0     0    0   0   0   0     0  
10   0   0   0     0    0   0   0   0     0  
11   0   0   0     0    0   0   0   0     0  
12   0   0   0     0    0   0   0   0     0  
13   0   0   0     0    0   0   0   0     0  
14   0   0   0     0    0   0   0   0     0  
15   0   0   0     0    0   0   0   0     0  
16   0   0   0     0    0   0   0   0     0  
17   0   0   0     0    0   0   0   0     0  
18   0   0   0     0    0   0   0   0     0  
19   0   0   0     0    0   0   0   0     0  

[20 rows x 2483 columns]

In [23]:
print(len(bow_vectorizer.get_feature_names()))
#bow_vectorizer.get_feature_names()

2483


In [24]:
#computer does not understand text, but it understand features
print(bow_train_features.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


## TFIDF

In [25]:
# build tfidf features' vectorizer and get features\
#Min_df stands for minimum document frequency,the less the number, the more specific the term
#‘l2’: Sum of squares of vector elements is 1

tfidf_vectorizer=TfidfVectorizer(min_df=30, 
                                 max_df=0.90,
                                 max_features=5000,
                                 norm='l2',
                                 smooth_idf=True,
#                                  th_idf=True,
                                 use_idf=True,
                                 ngram_range=(1,1))
tfidf_train_features = tfidf_vectorizer.fit_transform(train_corpus)  
tfidf_test_features = tfidf_vectorizer.transform(test_corpus) 

In [26]:
count_array1 = tfidf_test_features.toarray()
df = pd.DataFrame(data=count_array1,columns = tfidf_vectorizer.get_feature_names())
print(df.shape)
df.head(20)

#Different from count vectorizer. The scores are normalized to values between 0 and 1 
#so the vectors can  be used directly with machine learning algorithms.

(1739, 2483)


aa   ab      abil       abl     about      abov   absolut  abus   ac  \
0   0.0  0.0  0.000000  0.057382  0.035715  0.000000  0.000000   0.0  0.0   
1   0.0  0.0  0.000000  0.000000  0.000000  0.066679  0.000000   0.0  0.0   
2   0.0  0.0  0.008375  0.006894  0.000000  0.007157  0.007821   0.0  0.0   
3   0.0  0.0  0.000000  0.000000  0.045317  0.000000  0.000000   0.0  0.0   
4   0.0  0.0  0.000000  0.000000  0.000000  0.000000  0.000000   0.0  0.0   
5   0.0  0.0  0.000000  0.000000  0.009081  0.000000  0.033101   0.0  0.0   
6   0.0  0.0  0.000000  0.000000  0.000000  0.000000  0.000000   0.0  0.0   
7   0.0  0.0  0.000000  0.000000  0.000000  0.000000  0.000000   0.0  0.0   
8   0.0  0.0  0.000000  0.000000  0.000000  0.000000  0.000000   0.0  0.0   
9   0.0  0.0  0.000000  0.000000  0.000000  0.055358  0.000000   0.0  0.0   
10  0.0  0.0  0.000000  0.000000  0.000000  0.000000  0.000000   0.0  0.0   
11  0.0  0.0  0.000000  0.000000  0.000000  0.000000  0.000000   0.0  0.0   
12  0.0  0.0  0.000000  0.000000  0.000000  0.000000  0.000000   0.0  0.0   
13  0.0  0.0  0.000000  0.000000  0.044948  0.000000  0.000000   0.0  0.0   
14  0.0  0.0  0.000000  0.000000  0.085037  0.047278  0.000000   0.0  0.0   
15  0.0  0.0  0.000000  0.000000  0.000000  0.000000  0.000000   0.0  0.0   
16  0.0  0.0  0.000000  0.013241  0.041205  0.000000  0.000000   0.0  0.0   
17  0.0  0.0  0.000000  0.000000  0.025678  0.000000  0.000000   0.0  0.0   
18  0.0  0.0  0.000000  0.000000  0.000000  0.000000  0.000000   0.0  0.0   
19  0.0  0.0  0.000000  0.000000  0.000000  0.000000  0.000000   0.0  0.0   

      accept  ...  yourself   yr   yw   zd  zero  zip   zm   zt   zw  zzzz  
0   0.000000  ...       0.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  0.0   0.0  
1   0.000000  ...       0.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  0.0   0.0  
2   0.007165  ...       0.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  0.0   0.0  
3   0.000000  ...       0.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  0.0   0.0  
4   0.000000  ...       0.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  0.0   0.0  
5   0.015163  ...       0.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  0.0   0.0  
6   0.000000  ...       0.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  0.0   0.0  
7   0.000000  ...       0.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  0.0   0.0  
8   0.000000  ...       0.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  0.0   0.0  
9   0.000000  ...       0.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  0.0   0.0  
10  0.000000  ...       0.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  0.0   0.0  
11  0.000000  ...       0.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  0.0   0.0  
12  0.000000  ...       0.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  0.0   0.0  
13  0.000000  ...       0.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  0.0   0.0  
14  0.000000  ...       0.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  0.0   0.0  
15  0.000000  ...       0.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  0.0   0.0  
16  0.000000  ...       0.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  0.0   0.0  
17  0.000000  ...       0.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  0.0   0.0  
18  0.000000  ...       0.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  0.0   0.0  
19  0.000000  ...       0.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  0.0   0.0  

[20 rows x 2483 columns]

## Function for training testing and evaluating

In [42]:
# define a function that trains the model, performs predictions and evaluates the predictions
def train_predict_evaluate_model(classifier, 
                                 train_features, train_labels, 
                                 test_features, test_labels):
    # build model. fit(x,y)    
    classifier.fit(train_features, train_labels)
    # predict using model
    predictions = classifier.predict(test_features) 
    # evaluate model prediction performance   
    '''get_metrics(true_labels=test_labels, 
                predicted_labels=predictions)'''
    print(metrics.classification_report(test_labels,predictions))
    return predictions, metrics.accuracy_score(test_labels,predictions)    

In [39]:
from sklearn.naive_bayes import MultinomialNB # import naive bayes
from sklearn.tree import DecisionTreeClassifier # import Decision Tree
from sklearn.ensemble import RandomForestClassifier # import random forest

In [29]:
# assign naive bayes function to an object
mnb = MultinomialNB()
#The F1-score combines the precision and recall of a classifier into a single metric by taking their harmonic mean.
#It is primarily used to compare the performance of two classifiers. 
#Suppose that classifier A has a higher recall, and classifier B has higher precision. 
#In this case, the F1-scores for both the classifiers can be used to determine which one produces better results

#Support is the number of actual occurrences of the class in the specified dataset
# predict and evaluate naive bayes
mnb_bow_predictions, mnb_bow_accuracy = train_predict_evaluate_model(classifier=mnb,
                                           train_features=bow_train_features,
                                           train_labels=train_labels,
                                           test_features=bow_test_features,
                                           test_labels=test_labels)

#Support is nothing but the number of test samples available for testing(there are 1739 Total test samples available)
#Test samples that belong to class 0 is 1166

              precision    recall  f1-score   support

           0       0.91      0.99      0.95      1194
           1       0.98      0.79      0.87       545

    accuracy                           0.93      1739
   macro avg       0.95      0.89      0.91      1739
weighted avg       0.93      0.93      0.93      1739



## Naive Bayes Confusion Matrix Bag of Words Features

In [43]:
confusion_matrix(test_labels, mnb_bow_predictions)

NameError: name 'confusion_matrix' is not defined

## Naive Bayes Binary Feature Selection

In [ ]:
bow_vectorizer_binary=CountVectorizer(min_df=30, max_df=0.90,max_features=5000,ngram_range=(1,1), binary=True)
# print(bow_vectorizer)
#In short, fit is used to train the feature model, once it's trained you can use that model to apply to the text data
bow_train_features_binary = bow_vectorizer_binary.fit_transform(train_corpus)
#apply model to test data
bow_test_features_binary = bow_vectorizer_binary.transform(test_corpus)

In [44]:
mnb_bow_predictions_binary, mnb_bow_accuracy_binary = train_predict_evaluate_model(classifier=mnb,
                                           train_features=bow_train_features_binary,
                                           train_labels=train_labels,
                                           test_features=bow_test_features_binary,
                                           test_labels=test_labels)

              precision    recall  f1-score   support

           0       0.97      1.00      0.98      1172
           1       0.99      0.94      0.96       567

    accuracy                           0.98      1739
   macro avg       0.98      0.97      0.97      1739
weighted avg       0.98      0.98      0.98      1739



## Naive Bayes Confusion Matrix Binary Features

In [45]:
confusion_matrix(test_labels, mnb_bow_predictions_binary)

array([[1167,    5],
       [  36,  531]])

In [46]:
# predict and evaluate naive bayes with TFIDF Features
mnb_tfidf_predictions, mnb_tfidf_accuracy = train_predict_evaluate_model(classifier=mnb,
                                           train_features=tfidf_train_features,
                                           train_labels=train_labels,
                                           test_features=tfidf_test_features,
                                           test_labels=test_labels)

              precision    recall  f1-score   support

           0       0.96      0.99      0.98      1194
           1       0.98      0.92      0.95       545

    accuracy                           0.97      1739
   macro avg       0.97      0.96      0.96      1739
weighted avg       0.97      0.97      0.97      1739



## Confusion Matrix Naive Bayes TFIDF Features

In [39]:
confusion_matrix(test_labels, mnb_tfidf_predictions)

array([[1166,    6],
       [  58,  509]])

## Decision Trees

In [48]:
#Bag of Words
# assign decision tree function to an object
dt = DecisionTreeClassifier()

# predict and evaluate decision tree
dt_bow_predictions, dt_bow_accuracy = train_predict_evaluate_model(classifier=dt,
                                                               train_features=bow_train_features,
                                                               train_labels=train_labels,
                                                               test_features=bow_test_features,
                                                               test_labels=test_labels)

              precision    recall  f1-score   support

           0       0.97      0.95      0.96      1194
           1       0.90      0.94      0.92       545

    accuracy                           0.95      1739
   macro avg       0.94      0.95      0.94      1739
weighted avg       0.95      0.95      0.95      1739



## Confusion Matrix Decision Tree Bag of Words Feature Selection

In [37]:
confusion_matrix(test_labels, dt_bow_predictions)

array([[1128,   44],
       [  30,  537]])

## Binary Decision Trees Performance

In [46]:
# predict and evaluate decision tree
dt_bow_predictions_binary, dt_bow_accuracy_binary = train_predict_evaluate_model(classifier=dt,
                                                               train_features=bow_train_features_binary,
                                                               train_labels=train_labels,
                                                               test_features=bow_test_features_binary,
                                                               test_labels=test_labels)

              precision    recall  f1-score   support

           0       0.97      0.95      0.96      1172
           1       0.91      0.94      0.92       567

    accuracy                           0.95      1739
   macro avg       0.94      0.95      0.94      1739
weighted avg       0.95      0.95      0.95      1739



## Confusion Matrix Decision tree Binary Feature Selection

In [47]:
confusion_matrix(test_labels, dt_bow_predictions_binary)

array([[1119,   53],
       [  36,  531]])

In [50]:
#TFIDF 
# predict and evaluate decision tree
dt_tfidf_predictions, dt_tfidf_accuracy = train_predict_evaluate_model(classifier=dt,
                                           train_features=tfidf_train_features,
                                           train_labels=train_labels,
                                           test_features=tfidf_test_features,
                                           test_labels=test_labels)

              precision    recall  f1-score   support

           0       0.98      0.96      0.97      1194
           1       0.91      0.95      0.93       545

    accuracy                           0.95      1739
   macro avg       0.94      0.95      0.95      1739
weighted avg       0.95      0.95      0.95      1739



In [34]:
dt_tfidf_predictions

array([0, 1, 0, ..., 1, 1, 1])

## Confusion Matrix Decision Tree TFIDF Features selection

In [35]:
confusion_matrix(test_labels, dt_tfidf_predictions)

array([[1117,   55],
       [  36,  531]])

## Random Forest

In [54]:
# assign random forest function to an object
rf = RandomForestClassifier(criterion="entropy")

# predict and evaluate random forest
rf_bow_predictions, rf_bow_accuracy = train_predict_evaluate_model(classifier=rf,
                                           train_features=bow_train_features,
                                           train_labels=train_labels,
                                           test_features=bow_test_features,
                                           test_labels=test_labels)

              precision    recall  f1-score   support

           0       0.98      1.00      0.99      1194
           1       0.99      0.96      0.97       545

    accuracy                           0.98      1739
   macro avg       0.99      0.98      0.98      1739
weighted avg       0.98      0.98      0.98      1739



## Confusion Matrix Bag of Words Random Forest

In [36]:
confusion_matrix(test_labels, rf_bow_predictions)

array([[1170,    2],
       [  35,  532]])

## Random Forest Binary 

In [33]:
rf_bow_predictions_binary, rf_bow_accuracy_binary = train_predict_evaluate_model(classifier=rf,
                                           train_features=bow_train_features_binary,
                                           train_labels=train_labels,
                                           test_features=bow_test_features_binary,
                                           test_labels=test_labels)

              precision    recall  f1-score   support

           0       0.98      1.00      0.99      1194
           1       0.99      0.96      0.97       545

    accuracy                           0.98      1739
   macro avg       0.99      0.98      0.98      1739
weighted avg       0.98      0.98      0.98      1739



In [60]:
confusion_matrix(test_labels, predict_rf_binary)

array([[1189,    5],
       [  24,  521]])

In [59]:
predict_rf_binary = pd.Series(rf_bow_predictions_binary)


In [31]:
type(test_labels, predict_rf_binary)

pandas.core.series.Series

In [57]:
predict_rf = pd.Series(rf_tfidf_predictions)

In [53]:
# predict and evaluate random forest
rf_tfidf_predictions, rf_tfidf_accuracy = train_predict_evaluate_model(classifier=rf,
                                           train_features=tfidf_train_features,
                                           train_labels=train_labels,
                                           test_features=tfidf_test_features,
                                           test_labels=test_labels)

              precision    recall  f1-score   support

           0       0.98      1.00      0.99      1194
           1       0.99      0.95      0.97       545

    accuracy                           0.98      1739
   macro avg       0.98      0.97      0.98      1739
weighted avg       0.98      0.98      0.98      1739



In [25]:
rf_tfidf_accuracy

0.9821736630247269

In [55]:
from sklearn.metrics import confusion_matrix

## TFIDF Random Forest Confusion Matrix

In [58]:
confusion_matrix(test_labels, predict_rf)

array([[1190,    4],
       [  28,  517]])

In [ ]:
mnb_tfidf_accuracy

In [61]:
accuracy_dict = {}
for m in ["mnb","dt","rf"]:
    accuracy_dict[m] = {}
    for f in ["bow","tfidf"]:
        exec('accuracy_dict["{}"]["{}"] = {}_{}_accuracy'.format(m, f, m, f))
        
#Accuracy Matrix
pd.DataFrame(accuracy_dict).rename(columns={"mnb":"Naive Bayes", 
                                            "dt":"Decision Tree", 
                                            "rf":"Random Forest"}, 
                                   index={"bow":"Bag-of-words",
                                          
                                          "tfidf":"TFIDF", 
                                          "avgwv":"Word2Vec"})

Naive Bayes  Decision Tree  Random Forest
Bag-of-words     0.928120       0.948821       0.983899
TFIDF            0.970098       0.953422       0.981599